### ISSUE TITLE
Use /usr/libexec/java_home for JAVA_HOME paths

### ISSUE THREAD

**Issue by jvz** [ivankrylov/onSpinWaitMultiReleaseJar#1]
Instead of hard-coded paths, at least on macOS, you can set:

```make
JDK8 := $(shell /usr/libexec/java_home -v 1.8)
JDK9 := $(shell /usr/libexec/java_home -v 9)
```

**Comment by ivankrylov** [comment]
Thank you! I pushed your change. I should have thought of this myself.
https://github.com/ivankrylov/onSpinWaitMultiReleaseJar/commit/29c22e3889c10b988ad53e94e8e6ebba28f88d85#diff-b67911656ef5d18c4ae36cb6741b7965

This little project started as something I wanted to try in 5 minutes and then I wanted to show this to Gil Tene and then I figured I should push it somewhere globally.

**Comment by jvz** [comment]
I've suggested the use of `onSpinWait()` to three separate projects, and an approach like this could be super useful. All the asynchronous disruptors and similar projects can benefit from this new feature.

**Comment by ivankrylov** [comment]
Thanks. If you would have any performance numbers that show (or don't 
show) any gain with onSpinWait - I'd love to hear.
And if by chance you would be using agrona or org.performancehints on 
Azul's Zing - Zing will honor ThreadHints.onSpinWait() even on older JDKs.

Thanks,
Ivan
